### ISSUE TITLE
HtmlUnit tests fail with koji

### ISSUE THREAD

**Issue by rapgro** [JWebUnit/jwebunit#5]
HtmlUnit tests fail with 503 Service Unavailable in a chroot environment like koji is. I can not reproduce the errors locally. Any ideas what causes this?

```
Running net.sourceforge.jwebunit.htmlunit.RefreshHandlerTest
Tests run: 3, Failures: 1, Errors: 2, Skipped: 0, Time elapsed: 2.31 sec <<< FAILURE! - in net.sourceforge.jwebunit.htmlunit.RefreshHandlerTest
testChangeRefreshHandler(net.sourceforge.jwebunit.htmlunit.RefreshHandlerTest)  Time elapsed: 1.435 sec  <<< ERROR!
net.sourceforge.jwebunit.exception.TestingEngineResponseException: unexpected status code [503] at URL: [http://localhost:8082/jwebunit/RefreshHandlerTest/testPage.html]
    at net.sourceforge.jwebunit.htmlunit.RefreshHandlerTest.testChangeRefreshHandler(RefreshHandlerTest.java:96)
Caused by: com.gargoylesoftware.htmlunit.FailingHttpStatusCodeException: 503 Service Unavailable for http://localhost:8082/jwebunit/RefreshHandlerTest/testPage.html
    at net.sourceforge.jwebunit.htmlunit.RefreshHandlerTest.testChangeRefreshHandler(RefreshHandlerTest.java:96)
testAlternateRefreshHandler(net.sourceforge.jwebunit.htmlunit.RefreshHandlerTest)  Time elapsed: 0.024 sec  <<< ERROR!
net.sourceforge.jwebunit.exception.TestingEngineResponseException: unexpected status code [503] at URL: [http://localhost:8082/jwebunit/RefreshHandlerTest/testPage.html]
    at net.sourceforge.jwebunit.htmlunit.RefreshHandlerTest.testAlternateRefreshHandler(RefreshHandlerTest.java:75)
Caused by: com.gargoylesoftware.htmlunit.FailingHttpStatusCodeException: 503 Service Unavailable for http://localhost:8082/jwebunit/RefreshHandlerTest/testPage.html
    at net.sourceforge.jwebunit.htmlunit.RefreshHandlerTest.testAlternateRefreshHandler(RefreshHandlerTest.java:75)
testDefaultRefreshHandler(net.sourceforge.jwebunit.htmlunit.RefreshHandlerTest)  Time elapsed: 0.028 sec  <<< FAILURE!
java.lang.AssertionError: 
msg was not as expected.
[unexpected status code [503] at URL: [http://localhost:8082/jwebunit/RefreshHandlerTest/testPage.html]]
    at net.sourceforge.jwebunit.htmlunit.RefreshHandlerTest.testDefaultRefreshHandler(RefreshHandlerTest.java:55)
[…]
```

**Comment by rapgro** [comment]
Ping? Maybe any restrictions in network or generally available resources. The port for Jetty (8082) may be blocked somehow.

**Comment by henryju** [comment]
Hi, I don't have the time to investigate, but indeed it may be caused by some restrictions in chroot environment.

**Comment by rapgro** [comment]
Not reproducible any more.
